version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - backend

  api:
    build: ./backend
    container_name: my-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/customer_db
    depends_on:
      - mongodb
    networks:
      - backend

networks:
  backend:
    driver: bridge 